### ISSUE TITLE
Add `type` to `runReadQuery` RPC response `columns` contained object

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/go-tableland#188]
### User Story
A simple read query returns the columns and rows for a particular table. However, for each column, it is not clear what the _type_ on the column is. Namely, if I create a column of `id`, there's no way to directly know what this type should be without some specific SQL knowledge.

As an example, I would have to run `select sql from sqlite_schema where name='rest_api_5_85'` (see query [here](https://testnet.tableland.network/query?s=select%20sql%20from%20sqlite_schema%20where%20name=%27rest_api_5_85%27)), which returns a row of `CREATE TABLE rest_api_5_85 (id INT) STRICT`. Then, I'd have to parse that response etc. to get the actual type.

### Requirements
Add `type` to each object returned in the `runReadQuery` RPC response's `columns` array:
```
{
  "columns": [
    {
      "name": "id",
      "type": "int"
    }
  ],
  "rows": [
    [
      0
    ]
  ]
}

**Comment by brunocalza** [comment]
hey @dtbuchholz Exploring this a bit. 

This is something folks discussed in the past, but don't quite remember the outcomes of those conversations. I agree that having a type is handy in a lot of situations. 

Can you elaborate more on what is trying to be accomplished with that new field and how it helps? Just trying to get the full picture and see if we are not missing any other potential solution.

**Comment by brunocalza** [comment]
Just want to mention another nuance about this. There are two cases to be differentiated:
1. the type of the columns of a `CREATE` statement
2. the type of a `SELECT` column result

If we do `SELECT * FROM rest_api_5_85`, it's obvious it should return type `int` for `id` because `CREATE TABLE rest_api_5_85 (id INT)`. That's case `1`.

However, what if I do `SELECT count(1) FROM rest_api_5_85`? That's case `2`. `count(1)` is not a column with a type, it's calculated on the fly. What type should it be? It seems reasonable to return `int` for that as well. 

And what if we have `SELECT 3.1415 FROM rest_api_5_85`? What type is `3.1415`? Should it be Go's `float`, JavaScript's `number`, or SQLite's `real`? 

We also work with JSON. For example, `SELECT json_object(...) FROM ...` that returns a JSON and not a string (because of the NFT use case). Should we create the type `json` for that SELECT result?

---
If we want a response like:

```
{
  "columns": [
    {
      "name": "id",
      "type": "int"
    }
  ],
  "rows": [
    [
      0
    ]
  ]
}
```

makes sense to treat everything as case `2` and only care about the type of SELECT column result (and not the type defined in the `CREATE` statement). That's a bit more complicated because we have to infer the type of things like `count(1)`, `3.1415`, `json_obect(...)`, or any other arbitrary `expr`. And possibly creates new types such as `json`. That means we'd have two different kinds of types: the ones from a `CREATE` statement (`text`, `int`, `any`, `blob`, ...) and the types of a SELECT column result.

On the other hand, if we just want to provide a way for users to discover the types of the columns of a table, we can create an endpoint that returns the schema of a table.
