### ISSUE TITLE
Add support for a `tableland.network` gateway, redirecting to Tableland testnet or mainnet

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/go-tableland#261]
**Is your feature request related to a problem? Please describe.**
Register & use a `tableland.network` domain that handles redirects to the Tableland testnet or mainnet gateways via inference.

**Describe the solution you'd like** (via @sanderpick)
Ultimately, we want this:
- Tableland testnet only deals with evm testnets
- Tableland mainnet only deals with evm mainnets

This means that `chainID` actually infers the Tableland network. So, instead of standing up some new gateway like `mainnet.tableland.network` and requiring devs to make changes to their contracts, we can just alias `testnet.tableland.network` with `tableland.network` and create some redirect rules:
- If `chainID` is an evm testnet, permanent redirect to `testnet.tableland.network` if need be
- If `chainID` is an evm mainnet, permanent redirect to `tableland.network` if need be

**Describe alternatives you've considered**
As noted, a dedicated `mainnet.tableland.network` was considered, but the solution above makes any future migration much more seamless. 

**Additional context**
This reduces the need to update an ERC721 contract's `tokenURI` (or other methods) that reference the Tableland gateway. It alleviates some friction points, especially, if a contract was not upgradable and couldn't change the URI itself.

**Comment by dtbuchholz** [comment]
One other idea that was floated by @andrewxhill was adding versioning to the gateway, which aligns with @carsonfarmer's current API overhaul design, too. 

The idea also mentioned using `gateway.tableland.xyz`, which I'm mainly noting here because leveraging the word `gateway` might be a nice little DX play: it helps describe what a gateway is. Maybe we implement `tableland.gateway` (or `gateway.tableland`) instead of `tableland.network`? No strong opinion...might be easier to maintain the general format of what we already have.

(Also, perhaps I should have created this as a discussion vs. issue...can move there if needed)

**Comment by sanderpick** [comment]
@brunocalza or @jsign you guys have thoughts here? tl;dr, create ability to redirect based on chainID to some configured hosts in the config. we'd have a testnet and mainnet host in the config.

related to https://github.com/tablelandnetwork/go-tableland/issues/287

**Comment by jsign** [comment]
Not every API endpoint has `{chainID}` information today; some examples:
- `/query` endpoint doesn't need `{chainID}` information since you can join tables in the same network (requested by #287).
- `/schema/{table_name}` doesn't have `{chainID}` information since the table name uniquely identifies the table, so it isn't needed from the route or SIWE.

In those two cases, the way to infer the redirection isn't that trivial, since there's no `{chainID}` in the path or headers, but it's API dependent (e.g: parsing the query, or parsing path-subpaths to look for patterns to be maintained). If tomorrow we create a new API, we should always think how to create the appropriate custom  (since isn't always headers or path) rule in the reverse proxy, and potentially program that as part of the main work.

It can also produce some weird behavior from the user side. For example, `/schema/{table_name}` would give you info from testnet, and you might expect that in some other API that has relevant mainnet information, you can access that table; but since the backends are different validators you might get some `table not found` which is technically correct if this second API routed to mainnet (for whatever rule it has, which is hard to model since might be custom). The point is this might create incoherence between APIs in ways that might be surprising.

**Comment by sanderpick** [comment]
Good points. 

The main concern is providing some easy migration path for folks that have tables on mainnets (Ethereum, etc.) that are referenced by in `tokenURI` (or similar) methods over the current Tableland "testnet". Right now, we plan on migrating those tables to Tableland mainnet. We don't want folk to have to update the Tableland host in their contracts. The problem is probably obvious, just outlining it here to be clear.

I think #287 takes precedence over this concern. After that work, as you say, there is no feasible way to create a reverse proxy that can handle redirects across all APIs that are used in contracts today. 

At this point, I think we want to strongly encourage people to allow updating any reference to a Tableland host in their contacts, eg, in `baseURI`s, etc. We can continue to think about creating some nicer migration path.
