### ISSUE TITLE
Separate testnet and mainnet networks

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/go-tableland#287]
This came up in a chat with @andrewxhill. He pointed out that allowing JOINs between testnet chains and mainnet chains might setup some bad expectations.

Is there an easy way for us to ensure all tables involved in a query are either on a testnet or on a mainnet?

**Comment by jsign** [comment]
Now, I think this request might imply something deeper. Making the above sounds like we want to isolate mainnet chains from tesntet chains, which feels like wanting to run in a single validator on two separate networks. Maybe this means we should recommend running two different validators, one for mainnet and one for testnet? I say this because "not mixing" testnet and mainnet tables might not only make sense for read queries, but actually for everything in the protocol.

For example, if in the future we want to provide a service where a validator tells all the tables it's running: it makes sense that it will tell both testnet and mainnet ones? Because the idea here is that you won't be able to join, so it might be odd.
Also, if we come up with other validator processes such as committing state of tables, we want to mix both testnet and mainnet worlds? Same with potential tokenomics actions?

Users can't do read-query joins if testnet and mainnet tables run in two separate validators. (Pretty obvious, but just for completeness).

Of course, this would mean that operators would have to run two validator nodes instead of one; but if both worlds are separate then sounds obvious. We could also think about a single validator syncing chains grouped in "partitions", where each "partition" would be a different SQLite database. That's almost the same as two separate validators but ran in a single process. (Kind of a multi-tier validator (separate `registry`, `system_*` tables, etc). Not sure it's worth it since it might be better not to share hardware resources between testnet and mainnets).

Now, if we keep running tables in the same validator, we could walk the AST and detect which tables are targeted after we parse the read-query. If there's at least one table in mainnet and testnet, we could make the query fail at parsing time. But my point above is mostly thinking further if we might need to have a way to make this separation not only for read-queries, but maybe for more things, so this might not be the best approach.

**Comment by sanderpick** [comment]
Good points. Total separation is the cleanest solution to the JOINs issues, and would prevent us from having to solve additional related issues in the future around table state / security and economics.

**Comment by asutula** [comment]
Separate validators sounds right. Image a scenario where there is a new version of the validator that we want to roll out to testnet for a period of time for testing before the mainnet upgrade. That would only be possible with this separation in place. Seems like this solves many problems at once.

**Comment by jsign** [comment]
I'll close this issue since all this work was split into multiple tasks that were already done, and the tail of the remaining tasks are part of https://github.com/orgs/tablelandnetwork/projects/58.
