### ISSUE TITLE
[GOT-33] Test framework with SQL fuzzer to test out new spec language features

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/go-tableland#333]
From a conversation on Discord... it would be pretty cool to have a testing framework where we could just test out adding features to our SQL language spec and run them with a fuzzer or something using a simulated network, to try to catch non-determinism.

Questions like, "what if we added sub-selects to write queries, does that lead to non-determinism?" could be answered in an open and testable framework, and could be run via CI etc.

<sub>[GOT-33](https://linear.app/tableland/issue/GOT-33/test-framework-with-sql-fuzzer-to-test-out-new-spec-language-features)</sub>

**Comment by brunocalza** [comment]
When I was building the parser I started a side project related to this. I was aiming to generate a random SQL from our grammar to find flaws in our grammar. 

The implementation was pretty much navigating the grammar rules randomly (from the root, choose a random derivation rule) until you reach a terminal node. Then, you generate a random value for that node according to its type.

I made some progress, but I was having a hard time figuring out how to stop the derivation process because some derivation paths are circular (a -> b -> c -> a). 

So I kind of stopped working on that because it was consuming too much of my time

but anyways, seems like a nice tool to have in our test suite
